- name: Debug – show workspace
  run: |
    pwd
    ls -l
    find . -iname "dockerfile"

- name: Build Docker image
  run: |
    docker build \
      --no-cache \
      --progress=plain \
      -f $GITHUB_WORKSPACE/Dockerfile \
      -t erickshaw-backend \
      $GITHUB_WORKSPACE
